### ISSUE TITLE
Some comparison points with bonsai

### ISSUE THREAD

**Issue by szandara** [besok/forester#33]
Could you please share some comparisons with bonsai https://github.com/Sollimann/bonsai? I am looking for a long-term solution and am keen to know where my use cases are fitter.

**Comment by besok** [comment]
I will be into it in a couple of days.
Shortly, I can say the following things:

###  Bonsai. Some observations
 - great and lightweight library for BT. 
 - very straightforward API. In particular, The API allows creating the BT right from rust code. 
 It works brilliantly for small trees
 - For complex projects, the lib will require creating an extra layer of abstraction, since out of the box it seems a bit cumbersome.
 - Super lightweight. It doesn't use tokio or other lib which is cool.
 - The project is oriented(as far as I see) in the first turn to the game industry.

### Forester
The first distinction is the goal. This framework is oriented in the first turn to robotics. Essentially, what I am interested in is the research in 2 main directions:
 - Introducing the high-level dsl with the bt to reduce the redundancy and fold the complex subtrees (a hypothesis)
 - Combining the practices of Deep Learning with BTs and changing the BTs during execution relying on it
Although it provides the API to create the BTs in the rust code as well, it does seem less natural in comparison to Bonsai.

So, My reasoning is the following:
If your project will need to have some logic, orchestration with BT but it can be easily fitted into rust code. It will not need to be distributed on the different layers or systems, then Bonsai suits better.
If your project is in the area of ML/Robotics with the intention to use BT heavily and centralize the logic around it, probably Forester serves better.

**Comment by szandara** [comment]
Thank you, the Robotics use case really resonates with what we are trying to achieve. I will be keen to try it. Cheers
